### ISSUE TITLE
add a class_name to CurveMesh3D so it can be made and used in scripts

### ISSUE THREAD

**Issue by walksanatora** [cloudofoz/godot-curvemesh#1]
I am publishing my first addon and am having to use a slightly modified version of your addon so that I can embed your class in my scripts.
a simple `class_name` at the top of curvemesh3d.gd would be all thats needed to make use of this in scripts

**Comment by cloudofoz** [comment]
Hi @walksanatora , thank you for your interest in my add-on!

I've updated the code to include `class_name CurveMesh3D` at the top, which should make it easier to integrate the class directly in your scripts. This change is non-breaking, so it should be smooth to update. Let me know if it works well for you!

In case you need a workaround in the future, here are a couple of alternative ways to use a script without `class_name`:

1. **Define a constant**: Add the following at the beginning of your script to preload the class:
   ```gd
   const CurveMesh3D = preload("res://addons/curvemesh3d/curvemesh3d.gd")
   # ...
   var my_instance = CurveMesh3D.new()
   ```

2. **Inherit directly by path**: If you’re inheriting, you can specify the path in the `extends` statement:
   ```gd
   extends "res://addons/curvemesh3d/curvemesh3d.gd"
   ```

Good luck with your add-on!

Best,  
C.
